[project]
name = "pomme"
version = "0.1.0"
description = "A test version of Pomme"
authors = [{ name = "Li-Yin Young", email = "you@example.com" }]
dependencies = [
    "requests",  # Example of a PyPI package
    ]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

