name: Build Mac Wheel for Pomme

on:
  push:
    branches: ["universal_wheel"]

jobs:
  build-mac-wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-latest"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Build universal2 wheels
        uses: pypa/cibuildwheel@v3.0.1
        env:
            CIBW_ARCHS: universal2
            CIBW_PLATFORM: macos
            CIBW_SKIP: "*-musllinux*"

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
            name: macos-universal2-wheels
            path: wheelhouse/*.whl


