name: Pomme ci pipeline

on:
  push:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    -  name: Install dependencies
       run: |
         pip install -r requirements.txt

    - name: Build and install Pomme Python wrapper
      run: |
        python setup.py build_ext --inplace
        python setup.py install

    - name: Unit tests
      run: |
        py.test
        
    - name: Test the import
      run: |
        python tests/test_pomme_wrapper.py