name: Pomme ci pipeline

on:
  push:
    branches: ['*']

jobs:
  test:
    name: Run Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]


    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    -  name: Install dependencies
       run: |
         pip install -r requirements.txt

    - name: Build and install Pomme Python wrapper
      run: |
        python -m build
        pip install -e .

    - name: Unit tests
      run: |
        py.test
