name: Deploy to Github Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.0

jobs:
  build-wheel:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "windows-latest" ]
        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build
        run: |
          pip install build

      - name: Build wheel
        run: |
          python -m build

      - name: Upload wheel as artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.python-version }}
          path: dist/*.whl
  release:
    name: Create Release
    runs-on: windows-latest
    needs: build-wheel
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Flatten wheel files
        run: |
          mkdir all_wheels
          Get-ChildItem -Recurse dist\*.whl | Copy-Item -Destination all_wheels

      - name: List files in all_wheels
        run: Get-ChildItem all_wheels

      - name: Upload release assets
        uses: softprops/action-gh-release@v1

        with:
          files: all_wheels/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
