name: Pomme ci pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    -  name: Install dependencies
       run: |
         pip install -r requirements.txt

    - name: Build and install Pomme Python wrapper
      run: |
        python setup.py build_ext --inplace
        python setup.py install

    - name: Unit tests
      run: |
        py.test
