name: Build Mac Wheel for Pomme

on:
  push:
    tags:
      - 'v*.*.*'


jobs:
  release-mac-wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-latest", "macos-13"]
        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m build --wheel 

      - name: Upload wheels to Github Release
        uses: softprops/action-gh-release@v1

        with:
          draft: false
          files: dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


