name: Test the linux 2_28 wheels

on:
  push:
    branches: ["manylinux_2_28"]

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "cp311", "cp312", "cp313", "cp314" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: latest
      - name: Build wheels with cibuildwheel
        uses: pypa/cibuildwheel@v3.4.0
        env:
          CIBW_ARCHS: "x86_64"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_BUILD_FRONTEND: "build[uv]"
          CIBW_BUILD: "${{ matrix.python-version }}-*"
          # Skip to build musllinux and 32-bit manylinux wheels
          CIBW_SKIP: "*-musllinux* *-manylinux_i686"
          # Multi-threaded for C compiler
          MAKEFLAGS: "-j$(nproc)"
          CIBW_TEST_COMMAND: "python -c \"import pomme.pypomme\" && python {project}/tests/smoke_test_pypomme.py"

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.python-version }}
          path: wheelhouse/*.whl

  release-wheel:
    needs: build-wheel
    runs-on: ubuntu-latest
    steps:
      - name: Download built wheels
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true

      - name: Upload wheels to Github Release
        uses: softprops/action-gh-release@v1

        with:
          draft: true
          files: dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}





