name: Test the linux 2_28 wheels based on python 3.14 on Github actions

on:
  push:
    branches: ["manylinux_2_28"]

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "cp311-*", "cp312-*", "cp313-*", "cp314-*" ]
    env:
        CIBW_BUILD: ${{ matrix.python-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: latest
      - name: Build wheels with cibuildwheel
        uses: pypa/cibuildwheel@v3.4.0
        env:
          CIBW_ARCHS: "x86_64"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_BUILD_FRONTEND: "build[uv]"
          # Skip to build musllinux and 32-bit manylinux wheels
          CIBW_SKIP: "*-musllinux* *-manylinux_i686"
          # Multi-threaded for C compiler
          MAKEFLAGS: "-j$(nproc)"
          CIBW_TEST_COMMAND: "python -c \"import pomme.pypomme\" && python {project}/tests/smoke_test_pypomme.py"

      - name: Upload wheels to Github Release
        uses: softprops/action-gh-release@v1

        with:
          draft: true
          files: wheelhouse/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}





